### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by whollacsek** [graphile/migrate#31]
I'm trying to use graphile-migrate on Cloud Build with npx and it couldn't find tslib. I confirmed this by installing graphile-migrate into an empty package.json

```
$ graphile-migrate migrate
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/workspace/packages/web-app/database/node_modules/graphile-migrate/dist/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by benjie** [comment]
Oops; I've only consumed it from TypeScript projects which probably already have tslib installed. Could you raise a PR? I'm just finishing for the day :+1:
